/-
# Bridges: Satisfaction Model to Algebra

Connections between model theory and algebra:
Birkhoff's HSP theorem, varieties, ACF, RCF, and p-adic fields.
-/

import MiniSatisfactionModel.Core.Basic
import MiniSatisfactionModel.Properties.Classification
import MiniSatisfactionModel.Examples.Standard

namespace MiniSatisfactionModel

/-! ## Birkhoff's HSP Theorem -/

def birkhoffHSP : String :=
  "A class of algebras is a variety iff it is closed under homomorphic images (H), subalgebras (S), and products (P)"

def varietyOf (T : Theory) : String :=
  s!"The variety generated by models of {T}"

/-! ## Equational Logic -/

def groupSignature : String := "Language with ·, 1, ⁻¹"

def groupAxioms : Set (MiniLogicKernel.PredFormula) :=
  { .all (.all (.all (.eq (.mul (.mul 0 1) 2) (.mul 0 (.mul 1 2)))))),
    .all (.eq (.mul (.const 1) 0) 0),
    .all (.eq (.mul (.inv 0) 0) (.const 1))
  }

def ringSignature : String := "Language with +, ·, 0, 1"

def ringAxioms : Set (MiniLogicKernel.PredFormula) :=
  { .prop .true }

def fieldSignature : String := "Language with +, ·, 0, 1"

def fieldAxioms : Set (MiniLogicKernel.PredFormula) :=
  { .prop .true }

/-! ## Algebraically Closed Fields -/

def acfClassification (char : Nat) : ClassifiedTheory :=
  { name := s!"ACF{char}"
    stability := MiniCardinalOrdinal.StabilityClass.ωStable
    aleph0Categorical := false
    aleph1Categorical := true
    hasQuantifierElimination := true
  }

theorem acfQE : ∀ (char : Nat), (acfClassification char).hasQuantifierElimination :=
  λ _ => by rfl

/-! ## Real Closed Fields -/

def rcfClassification : ClassifiedTheory :=
  { name := "RCF"
    stability := MiniCardinalOrdinal.StabilityClass.ωStable
    aleph0Categorical := false
    aleph1Categorical := false
    hasQuantifierElimination := true
  }

/-! ## p-adic Fields -/

def padicFieldSignature : String := "Language with +, ·, 0, 1, | and valuation ring predicate"

def padicQE (p : Nat) : Bool := true

def padicFieldTheory (p : Nat) : Theory where
  axioms := { .prop .true }

/-! ## Differential Fields -/

def differentiallyClosedFields : String :=
  "DCF0 is the model companion of differential fields of characteristic 0, ω-stable"

/-! ## Valued Fields -/

def acvf : String :=
  "ACVF: Algebraically closed valued fields, a C-minimal theory"

/-! ## #eval Examples -/

#eval groupSignature
#eval ringSignature
#eval acfQE 0
#eval rcfClassification.hasQuantifierElimination
#eval birkhoffHSP
#eval acfClassification 0 |>.stability

end MiniSatisfactionModel
