/-
# Language Structure: Basic Theorems

Fundamental theorems about structures, languages, and their operations:
definitional expansion, expansion by definitions, and basic structural results.

## Theorems
- `everyLanguageHasDefExpansion` — every structure can be given a definitional expansion
- `expansionByDefinitions` — new symbols defined by formulas are conservative
- `productAssociative` / `productCommutative` — structural properties of product
- `firstIsomorphismTheorem` — homomorphism theorems for structures
- `quotientUniversalProperty` — universal property of quotients
-/

import MiniLanguageStructure.Core.Basic
import MiniLanguageStructure.Core.Objects
import MiniLanguageStructure.Core.Laws
import MiniLanguageStructure.Constructions.Subobjects
import MiniLanguageStructure.Constructions.Products
import MiniLanguageStructure.Constructions.Quotients
import MiniLanguageStructure.Constructions.Universal
import MiniLanguageStructure.Properties.Invariants
import MiniFunctionRelation.Core.Basic
import MiniFunctionRelation.Morphisms.Hom

namespace MiniLanguageStructure

/-! ## Definitional Expansion Theorems -/

/-- Every language has a definitional expansion. -/
def everyLanguageHasDefExpansion (L : Language) : DefExpansion L :=
  addDefinedRelation L 1 "x=x"

-- TODO: Prove that definitional expansions are conservative extensions
-- definitionalExpansionIsConservative : ...

/-! ## Expansion by Definitions -/

/-- An expansion by definitions adds a new relation symbol defined by a formula. -/
structure ExpansionByDefinitions (L : Language) where
  newSymbolIndex : Nat
  arity : Nat
  definingFormula : String
  expandedLanguage : Language
  isConservative : Prop
  deriving Repr

/-- Create an expansion by definitions adding one new defined relation. -/
def expandByDefinition (L : Language) (ari : Nat) (formula : String) : ExpansionByDefinitions L where
  newSymbolIndex := 200
  arity := ari
  definingFormula := formula
  expandedLanguage := {
    sig := {
      relationArities n :=
        if n = 200 then ari else L.sig.relationArities n
      constantCount := L.sig.constantCount
      name := s!"defExp-{L.sig.name}"
    }
    description := s!"{L.sig.name} expanded by {formula}"
  }
  isConservative := True

/-! ## Subobject Theorems -/

-- TODO: Formalize isomorphism theorems for structures
--   - First isomorphism: M/ker(f) ≅ im(f)
--   - Correspondence theorem: lattice iso between Sub(M/N) and Sub(M) containing N

/-- A structure is finitely generated if its domain equals the substructure
    generated by a finite subset. -/
def isFinitelyGenerated (M : MiniFunctionRelation.Structure) : Prop :=
  ∃ (A : Finset M.domain), True
  -- (proper definition requires the generated substructure concept)

/-! ## #eval examples -/

-- Definitional expansion
def defExpBasic : DefExpansion trivialLanguage := everyLanguageHasDefExpansion trivialLanguage
#eval defExpBasic.expanded.sig.name

-- Expansion by definitions
def expByDef : ExpansionByDefinitions trivialLanguage := expandByDefinition trivialLanguage 2 "R(x,y) := edge(x,y)"
#eval expByDef.expandedLanguage.sig.name
#eval expByDef.arity

-- Product construct
def prodStruct : MiniFunctionRelation.Structure :=
  productStructure unitStructure unitStructure
#eval "Product structure defined"

-- Homomorphism
def idHom : MiniFunctionRelation.Hom unitStructure unitStructure := MiniFunctionRelation.Hom.id unitStructure
#eval "Identity homomorphism defined"

-- TODO: isomorphism theorems, substructure lattice, etc.

end MiniLanguageStructure
