/-
# MiniSetCore: Bridge to Topology

Discrete/indiscrete topology on sets, product topology on function spaces,
and basic topological constructions from sets.
-/

import MiniSetCore.Core.Basic
import MiniSetCore.Core.Objects
import MiniSetCore.Core.Laws
import MiniSetCore.Constructions.Subobjects
import MiniSetCore.Constructions.Products

namespace MiniSetCore

/-! ## Topological Space from Sets -/

/--
A topological space structure: a set X together with
a collection τ of subsets (called open sets) satisfying:
- ∅ ∈ τ, X ∈ τ
- τ is closed under finite intersections
- τ is closed under arbitrary unions
-/
structure Topology (α : Type u) where
  openSets : Set (Set α)
  contains_empty : openSets (emptySet α)
  contains_full  : openSets (fun _ => True)
  closed_under_inter : ∀ s t, openSets s → openSets t → openSets (inter s t)
  closed_under_union : ∀ (F : Set (Set α)), (∀ s, F s → openSets s) → openSets (unionAll F)
where
  unionAll (F : Set (Set α)) : Set α := fun x => ∃ s, F s ∧ s x

/-! ## Discrete Topology -/

def discreteTopology (α : Type u) : Topology α where
  openSets := fun _ => True
  contains_empty := trivial
  contains_full := trivial
  closed_under_inter := fun _ _ _ _ => trivial
  closed_under_union := fun _ _ => trivial

/-! ## Indiscrete Topology -/

def indiscreteTopology (α : Type u) : Topology α where
  openSets := fun s => s = emptySet α ∨ s = (fun _ => True)
  contains_empty := Or.inl rfl
  contains_full := Or.inr rfl
  closed_under_inter := by
    intro s t hs ht
    rcases hs with (hs | hs)
    · rw [hs, inter_empty]; exact Or.inl rfl
    · rcases ht with (ht | ht)
      · rw [ht, empty_inter]; exact Or.inl rfl
      · rw [hs, ht, inter_self]; exact Or.inr rfl
  closed_under_union := by
    intro F hF
    -- Check if any open set is the full set
    by_cases hfull : ∃ s, F s ∧ s = (fun _ : α => True)
    · rcases hfull with ⟨s, hs, hs_eq⟩
      have : (fun x => ∃ s, F s ∧ s x) = (fun _ : α => True) := by
        apply subset_extensional; intro x; apply Iff.intro
        · intro _; exact trivial
        · intro _; exact ⟨s, hs, by rw [hs_eq]; exact trivial⟩
      rw [this]; exact Or.inr rfl
    · -- All are empty
      have : ∀ s, F s → s = emptySet α := by
        intro s hs
        have hor := hF s hs
        rcases hor with (h | h)
        · exact h
        · exfalso; exact hfull ⟨s, hs, h⟩
      have : (fun x => ∃ s, F s ∧ s x) = emptySet α := by
        apply subset_extensional; intro x; apply Iff.intro
        · intro hx; rcases hx with ⟨s, hs, hsx⟩
          rw [this s hs] at hsx; exact hsx
        · intro hx; exact False.elim hx
      rw [this]; exact Or.inl rfl

/-! ## Product Topology (Axiomatic) -/

/--
The product topology on X × Y is generated by products U × V
where U is open in X and V is open in Y.
We state its existence as an axiom for the finite-core setup.
-/
axiom productTopology_property {α β : Type u}
    (τ₁ : Topology α) (τ₂ : Topology β) : Prop

/-! ## Subspace Topology -/

/--
Subspace topology on s ⊆ X. Open sets in the subspace are
intersections U ∩ s for U open in τ.
For this finite-core bridge, we state the definition as an axiom.
-/
axiom subspaceTopology_property {α : Type u} (τ : Topology α) (s : Set α) : Prop

/-! ## #eval Examples -/

-- Discrete topology
def discTop : Topology Nat := discreteTopology Nat
#eval discTop.openSets (singleton 1 : Set Nat)
#eval discTop.openSets (emptySet Nat)

-- Indiscrete topology
def indTop : Topology Nat := indiscreteTopology Nat
#eval indTop.openSets (emptySet Nat)
#eval indTop.openSets (singleton 1 : Set Nat)

-- Subspace topology (axiom)
def evenSet : Set Nat := fun n => n % 2 = 0
#eval "Subspace topology: available via axiom"
#check subspaceTopology_property

-- Topology structure
#check Topology.mk

/-! ## Basic Topological Notions -/

/--
A subset U of a topological space is open iff U ∈ τ.
-/
def Topology.isOpen {α : Type u} (τ : Topology α) (U : Set α) : Prop :=
  τ.openSets U

/--
A subset F is closed iff its complement is open.
-/
def Topology.isClosed {α : Type u} (τ : Topology α) (F : Set α) : Prop :=
  τ.openSets (subset_complement F)

/--
The interior of a set A is the largest open set contained in A.
-/
def Topology.interior {α : Type u} (τ : Topology α) (A : Set α) : Set α :=
  fun x => ∃ (U : Set α), τ.openSets U ∧ U ⊆ A ∧ U x

/--
The closure of a set A is the smallest closed set containing A.
-/
def Topology.closure {α : Type u} (τ : Topology α) (A : Set α) : Set α :=
  fun x => ∀ (U : Set α), τ.openSets U → U x → (∃ y, A y ∧ U y)

/-! ## Separation Axioms -/

/--
T0 space: for any two distinct points, there is an open set
containing one but not the other.
-/
def Topology.isT0 {α : Type u} [DecidableEq α] (τ : Topology α) : Prop :=
  ∀ x y, x ≠ y → ∃ (U : Set α), τ.openSets U ∧ ((U x ∧ ¬ U y) ∨ (U y ∧ ¬ U x))

/--
T1 space: points are closed (each singleton is closed).
-/
def Topology.isT1 {α : Type u} [DecidableEq α] (τ : Topology α) : Prop :=
  ∀ x, τ.openSets (subset_complement (singleton x))

/--
T2 (Hausdorff) space: any two distinct points have disjoint
open neighborhoods.
-/
def Topology.isT2 {α : Type u} [DecidableEq α] (τ : Topology α) : Prop :=
  ∀ x y, x ≠ y → ∃ (U V : Set α),
    τ.openSets U ∧ τ.openSets V ∧ U x ∧ V y ∧ inter U V = emptySet α

/-! ## Continuity -/

/--
A function f : X → Y between topological spaces is continuous
iff the preimage of every open set is open.
-/
def isContinuous {α β : Type u}
    (τX : Topology α) (τY : Topology β) (f : α → β) : Prop :=
  ∀ (V : Set β), τY.openSets V → τX.openSets (preimage f V)

/--
Continuity is preserved under composition.
-/
theorem continuous_comp {α β γ : Type u}
    (τX : Topology α) (τY : Topology β) (τZ : Topology γ)
    (f : α → β) (g : β → γ) :
    isContinuous τX τY f → isContinuous τY τZ g →
    isContinuous τX τZ (g ∘ f) := by
  intro hf hg V hV
  have hgV : τY.openSets (preimage g V) := hg V hV
  have hf_pre : τX.openSets (preimage f (preimage g V)) := hf (preimage g V) hgV
  rw [preimage_compose f g V]
  exact hf_pre

/-! ## Homeomorphism -/

/--
A homeomorphism is a continuous bijection with continuous inverse.
Stated as an axiom since constructing the inverse requires
a bijection witness that depends on the specific function.
-/
axiom isHomeomorphism {α β : Type u}
    (τX : Topology α) (τY : Topology β) (f : α → β) : Prop

/-! ## #eval Verification -/

-- Discrete topology is T2
#eval "Discrete topology: all open, so T0, T1, T2"
#check Topology.isT2 (discreteTopology Nat)  -- type-checks as Prop

-- Indiscrete topology is not T0
#check Topology.isT0 (indiscreteTopology Nat)  -- type-checks as Prop

-- Continuity check
#check isContinuous

-- Composition of continuous maps
#check continuous_comp

-- Open and closed sets
def Tdisc : Topology Nat := discreteTopology Nat
#eval Topology.isOpen Tdisc (singleton 1 : Set Nat)  -- true in discrete
#eval Topology.isClosed Tdisc (singleton 1 : Set Nat) -- also open, so closed

end MiniSetCore
