/-
# MiniSetCore: Universal Constructions

Initial and terminal objects in the category of sets.
The empty set is initial; a singleton is terminal.
-/

import MiniSetCore.Core.Basic
import MiniSetCore.Core.Objects
import MiniSetCore.Core.Laws

namespace MiniSetCore

/-! ## Initial Object (Empty Set) -/

def initialSet (α : Type u) : Set α := emptySet α

theorem initial_unique {α : Type u} (s : Set α) :
    (∃! f : Set α → Set α, f (initialSet α) = s) := by
  refine ⟨fun _ => s, rfl, ?_⟩
  intro g hg
  funext t
  -- The constant map to s is unique
  apply hg.trans ?_
  -- This uniqueness holds only up to the property
  exact rfl

/--
Universal property of the initial set:
For any set s, there is exactly one function from the empty set to s.
-/
theorem initial_property {α : Type u} (s : Set α) :
    ∃! (f : Set α → Set α), f (emptySet α) = s := by
  refine ⟨fun _ => s, rfl, ?_⟩
  intro g hg
  funext x
  -- Since emptySet α x is always False, g can send it anywhere
  -- This is vacuous; any function with the property must equal (fun _ => s)
  exact hg

/-! ## Terminal Object (Singleton Set) -/

def terminalSet (α : Type u) [DecidableEq α] (a : α) : Set α := singleton a

/--
Universal property of the terminal set:
For any set s in the "Set" sense, there is a unique constant map
into a singleton.
-/
theorem terminal_property {α : Type u} [DecidableEq α] (a : α) (s : Set α) :
    ∃! (f : Set α → Set α), f s = singleton a := by
  refine ⟨fun _ => singleton a, rfl, ?_⟩
  intro g hg
  funext x
  exact hg.symm ▸ rfl

/-! ## Unique Maps -/

def initialMap {α β : Type u} (s : Set β) : Set α → Set β := fun _ => s

def terminalMap {α β : Type u} [DecidableEq β] (a : β) : Set α → Set β :=
  fun _ => singleton a

/-! ## Lift from Initial -/

def liftInitial {α β : Type u} (s : Set β) : Set α → Set β := fun _ => s

theorem liftInitial_factor {α β : Type u} (s : Set β) (f : Set α → Set β) :
    f (emptySet α) = s := by
  apply subset_extensional
  intro x; apply Iff.intro
  · intro hx; exfalso; exact hx
  · intro hx; exfalso
    -- This is vacuously true since we're proving about the empty set
    have : f (emptySet α) x := by
      -- but emptySet has no elements
      exact hx
    exact this

/-- The empty set is the only set that maps to everything. -/
theorem emptySet_is_initial {α : Type u} (s : Set α) :
    (emptySet α ⊆ s) := empty_subset s

/-! ## #eval Examples -/

-- Initial set is empty
#eval initialSet Nat 0
#eval initialSet Nat 42

-- Terminal set (singleton) membership
#eval terminalSet Nat 5 5
#eval terminalSet Nat 5 3

-- Initial map sends everything to a given set
def constSet : Set Nat := singleton 100
#eval initialMap constSet (singleton 1 : Set Nat) 100
#eval initialMap constSet (singleton 1 : Set Nat) 50

-- Terminal map sends everything to the chosen singleton
#eval terminalMap Nat 7 (singleton 1 : Set Nat) 7
#eval terminalMap Nat 7 (singleton 1 : Set Nat) 9

/-! ## Equalizers in Set -/

/--
The equalizer of two parallel functions f, g : X → Y is
E = {x ∈ X | f x = g x} with inclusion i : E → X.
-/
def equalizer {α β : Type u} (f g : α → β) : Set α :=
  fun x => f x = g x

/--
The universal property of the equalizer:
For any set Z with map h : Z → X such that f ∘ h = g ∘ h,
there is a unique map k : Z → E such that i ∘ k = h.
-/
theorem equalizer_universal {α β γ : Type u} (f g : α → β) (h : γ → α) :
    (∀ z, f (h z) = g (h z)) →
    (∀ z, equalizer f g (h z)) :=
  fun h_cond z => h_cond z

/-- The image of the mediating map lands in the equalizer. -/
def equalizerMediating {α β γ : Type u} (f g : α → β) (h : γ → α)
    (h_cond : ∀ z, f (h z) = g (h z)) : γ → Set α :=
  fun z => fun x => x = h z

/-! ## Pullbacks in Set -/

/--
The pullback of f : A → C and g : B → C is
P = {(a, b) ∈ A × B | f a = g b}.
-/
def pullback {α β γ : Type u} (f : α → γ) (g : β → γ) : Set (α × β) :=
  fun p => f p.1 = g p.2

/--
Universal property of the pullback:
Any pair of maps h : Z → A, k : Z → B such that f ∘ h = g ∘ k
factors uniquely through the pullback.
-/
def pullbackMediating {α β γ δ : Type u}
    (f : α → γ) (g : β → γ) (h : δ → α) (k : δ → β)
    (h_comm : ∀ d, f (h d) = g (k d)) : δ → α × β :=
  fun d => (h d, k d)

theorem pullback_universal {α β γ δ : Type u}
    (f : α → γ) (g : β → γ) (h : δ → α) (k : δ → β)
    (h_comm : ∀ d, f (h d) = g (k d)) (d : δ) :
    pullback f g (pullbackMediating f g h k h_comm d) :=
  h_comm d

/-! ## Pushouts in Set -/

/--
The pushout of f : C → A and g : C → B is
the disjoint union A ⊕ B modulo the equivalence relation
generated by (inl (f c)) ~ (inr (g c)).
In the Set category, this is A ⊕ B quotiented by
the smallest equivalence relation containing these pairs.
-/
def pushoutSet {α β γ : Type u} (f : γ → α) (g : γ → β) : Set (α ⊕ β) :=
  fun _ => True
-- The full construction requires quotient types which we
-- state axiomatically below.

/--
The pushout property: given maps h : A → D and k : B → D
such that h ∘ f = k ∘ g, there exists a unique map from the pushout.
-/
axiom pushout_property {α β γ δ : Type u}
    (f : γ → α) (g : γ → β) (h : α → δ) (k : β → δ) :
    (∀ c, h (f c) = k (g c)) →
    ∀ (x : α ⊕ β), δ

/-! ## Monos and Epis in Set -/

/--
In Set, monos are exactly injective functions.
-/
theorem mono_iff_injective {α β : Type u} (f : α → β) :
    isInjective f ↔ (∀ {γ : Type u} (g₁ g₂ : γ → α),
      f ∘ g₁ = f ∘ g₂ → g₁ = g₂) := by
  apply Iff.intro
  · intro h_inj γ g₁ g₂ h_eq
    funext x
    apply h_inj
    have : (f ∘ g₁) x = (f ∘ g₂) x := congrArg (fun φ => φ x) h_eq
    rw [Function.comp_apply, Function.comp_apply] at this
    exact this
  · intro h_mono x y h
    let g₁ : Unit → α := fun _ => x
    let g₂ : Unit → α := fun _ => y
    have h_comp : f ∘ g₁ = f ∘ g₂ := by
      funext u; simp [g₁, g₂, h]
    have h_eq : g₁ = g₂ := h_mono g₁ g₂ h_comp
    have : g₁ () = g₂ () := congrArg (fun φ => φ ()) h_eq
    simp [g₁, g₂] at this
    exact this

/--
In Set, epis are exactly surjective functions.
-/
theorem epi_iff_surjective {α β : Type u} (f : α → β) :
    isSurjective f ↔ (∀ {γ : Type u} (g₁ g₂ : β → γ),
      g₁ ∘ f = g₂ ∘ f → g₁ = g₂) := by
  apply Iff.intro
  · intro h_surj γ g₁ g₂ h_eq
    funext y
    rcases h_surj y with ⟨x, hx⟩
    have : (g₁ ∘ f) x = (g₂ ∘ f) x := congrArg (fun φ => φ x) h_eq
    rw [Function.comp_apply, Function.comp_apply, hx] at this
    exact this
  · intro h_epi
    intro y
    by_contra h
    push_neg at h
    -- Build two functions g₁, g₂ : β → Prop that differ only at y
    let g₁ : β → Prop := fun b => True
    let g₂ : β → Prop := fun b => if b = y then False else True
    have h_comp : g₁ ∘ f = g₂ ∘ f := by
      funext x; apply propext; apply Iff.intro
      · intro _; dsimp [g₂]; split <;> try exact trivial
        · rename_i h_eq; exfalso; exact h ⟨x, h_eq⟩
      · intro hx; exact trivial
    have h_g_eq : g₁ = g₂ := h_epi g₁ g₂ h_comp
    have : g₁ y = g₂ y := congrArg (fun φ => φ y) h_g_eq
    simp [g₁, g₂] at this

/-! ## #eval Verification -/

-- Equalizer
def f1 : Nat → Nat := fun x => x % 2
def f2 : Nat → Nat := fun x => x % 3
#eval equalizer f1 f2 0 -- 0 % 2 = 0 % 3 ✓
#eval equalizer f1 f2 1 -- 1 % 2 = 1, 1 % 3 = 1 ✓
#eval equalizer f1 f2 2 -- 2 % 2 = 0, 2 % 3 = 2 ✗

-- Pullback
def toMod2 : Nat → Nat := fun n => n % 2
def toMod3 : Nat → Nat := fun n => n % 3
#eval pullback toMod2 toMod3 (2, 3)  -- 2%2 = 0, 3%3 = 0 ✓
#eval pullback toMod2 toMod3 (2, 4)  -- 2%2 = 0, 4%3 = 1 ✗

-- Monos and Epis
#check mono_iff_injective
#check epi_iff_surjective

end MiniSetCore
