import MiniFunctionRelation.Core.Basic
import MiniFunctionRelation.Core.Syntax

namespace MiniFunctionRelation

/-
# Ultraproduct Construction

The ultraproduct of a family of structures modulo an ultrafilter.
-/

/-! ## Filters and Ultrafilters -/

structure Filter (I : Type) where
  sets : Set (Set I)
  univ_mem : Set.univ ∈ sets
  inter_closed : ∀ {A B : Set I}, A ∈ sets → B ∈ sets → A ∩ B ∈ sets
  superset_closed : ∀ {A B : Set I}, A ∈ sets → A ⊆ B → B ∈ sets
  empty_not_mem : ∅ ∉ sets

structure Ultrafilter (I : Type) extends Filter I where
  isUltra : ∀ (A : Set I), A ∈ sets ∨ (Set.univ \ A) ∈ sets

/-- The principal ultrafilter generated by element i. -/
def principalUltrafilter {I : Type} (i : I) : Ultrafilter I where
  sets := {A | i ∈ A}
  univ_mem := Set.mem_univ _
  inter_closed hA hB := Set.mem_inter hA hB
  superset_closed hA hAB := hAB hA
  empty_not_mem := by simp
  isUltra A := by
    classical
    by_cases h : i ∈ A
    · left; exact h
    · right; simp [h]

/-! ## Ultrapower of a single structure -/

def Ultrapower (M : Structure) (I : Type) (U : Ultrafilter I) : Structure where
  domain := I → M.domain
  predInterp p args :=
    {i : I | M.predInterp p (args.map (λ (f : I → M.domain) => f i))} ∈ U.sets
  constInterp c := λ _ => M.constInterp c

def diagonalEmbedding (M : Structure) (I : Type) (U : Ultrafilter I) :
    Hom M (Ultrapower M I U) where
  map x := λ _ => x
  preservesPred p args h := by
    simp [Ultrapower]
    have hset : {i : I | M.predInterp p
      ((args.map (λ (x : M.domain) => (λ (_ : I) => x))).map (λ (f : I → M.domain) => f i))}
      = Set.univ := by
      ext i; simp [h]
    rw [hset]
    exact U.univ_mem
  preservesConst c := rfl

theorem diagonalEmbedding_injective (M : Structure) (I : Type) (U : Ultrafilter I) [Inhabited I] :
    Function.Injective (diagonalEmbedding M I U).map := by
  intro x y h
  have h' := congrArg (λ f => f (default : I)) h
  simpa [diagonalEmbedding] using h'

/-! ## Ultraproduct of a family -/

structure FamilyStruct (I : Type) where
  struct : I → Structure

def Ultraproduct (I : Type) (fam : FamilyStruct I) (U : Ultrafilter I) : Structure where
  domain := (i : I) → (fam.struct i).domain
  predInterp p args :=
    {i : I | (fam.struct i).predInterp p (args.map (λ f => f i))} ∈ U.sets
  constInterp c := λ i => (fam.struct i).constInterp c

/-- Extra structure: an ultraproduct of a family contains the factors as 'sections'. -/
def Ultraproduct.constantSection (I : Type) (fam : FamilyStruct I) (U : Ultrafilter I)
    (c : Nat) : (Ultraproduct I fam U).domain :=
  λ i => (fam.struct i).constInterp c

/-- Reduced product (using filter, not necessarily ultrafilter). -/
def ReducedProduct (I : Type) (fam : FamilyStruct I) (F : Filter I) : Structure where
  domain := (i : I) → (fam.struct i).domain
  predInterp p args :=
    {i : I | (fam.struct i).predInterp p (args.map (λ f => f i))} ∈ F.sets
  constInterp c := λ i => (fam.struct i).constInterp c

def reducedDiagonalEmbedding (M : Structure) (I : Type) (F : Filter I) :
    Hom M (ReducedProduct I { struct := λ _ => M } F) where
  map x := λ _ => x
  preservesPred p args h := by
    simp [ReducedProduct]
    have hset : {i : I | M.predInterp p
      ((args.map (λ (x : M.domain) => (λ (_ : I) => x))).map (λ f => f i))}
      = Set.univ := by
      ext i; simp [h]
    rw [hset]
    exact F.univ_mem
  preservesConst c := rfl

/-! ## Concrete examples with finite index sets -/

def twoIndexUltrafilter : Ultrafilter Bool :=
  principalUltrafilter true

def exampleUltrapower : Structure :=
  Ultrapower {
    domain := Nat
    predInterp 0 args := match args with
      | [x, y] => x < y
      | _ => False
    predInterp _ _ := False
    constInterp _ := 0
  } Bool twoIndexUltrafilter

#eval (exampleUltrapower.constInterp 0) true
#eval (exampleUltrapower.constInterp 0) false

/-! ## Łoś's Theorem (documented statement) -/

/-- Łoś's theorem: truth in the ultraproduct = truth in U-almost all factors.
    The full proof requires induction on formula complexity. -/
def losTheoremStatement : Prop :=
  ∀ (I : Type) (fam : FamilyStruct I) (U : Ultrafilter I)
    (φ : Formula) (σ : Assignment (Ultraproduct I fam U)),
    (Ultraproduct I fam U).satisfiesFormula σ φ ↔
    {i : I | (fam.struct i).satisfiesFormula (λ (v : Nat) => σ v i) φ} ∈ U.sets

/-- The diagonal embedding is elementary (corollary of Łoś's theorem). -/
def diagonalEmbeddingElementary : Prop :=
  ∀ (M : Structure) (I : Type) (U : Ultrafilter I)
    (φ : Formula) (σ : Assignment M),
    M.satisfiesFormula σ φ ↔
    (Ultrapower M I U).satisfiesFormula
      (λ v => (diagonalEmbedding M I U).map (σ v)) φ

#eval "Ultraproduct.lean loaded — Filter, Ultrafilter, Ultrapower, ReducedProduct"

end MiniFunctionRelation
